version: '3.8'

name: bitwise

services:
  db:
    container_name: bitwise-db-dev
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          'admin',
          '--port',
          '27017',
          '--eval',
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 10
